version: '3.7'
services:
  service-1:
    image: benhesketh21/animal-app-1
    build: ./service-1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 2
  service-2:
    image: benhesketh21/animal-app-2
    build: ./service-2
    ports:
    - target: 5001
      protocol: tcp
    deploy:
      replicas: 2
    